# Generated by Django 4.1.13 on 2024-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='csv_file',
            field=models.FileField(upload_to='media/csv_files/'),
        ),
    ]
